// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Status struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Task struct {
	ID          int32         `json:"id"`
	Name        string        `json:"name"`
	StatusID    int32         `json:"status_id"`
	ParentID    sql.NullInt32 `json:"parent_id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
}
